fixing github action part 10

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -1,6 +1,6 @@
 name: Python Code Quality and Lint
 
-on: [push]
+on: [ push ]
 
 jobs:
   build:
@@ -10,19 +10,14 @@ jobs:
         uses: actions/checkout@v3
       - name: "Install Dependencies"
         run: |
-            pip install poetry
-            cd backend
-            poetry install
-            echo "OK"
-      - name: "Using 654wak654/python-lint@1.5.0"
-        uses: 654wak654/python-lint@1.5.0
+          pip install poetry
+          cd backend
+          poetry install
+          echo "OK"
+      - name: "Checking Code"
         with:
           # A list of all paths to test
           python-root-list: "backend"
-          # Use Pylint
-          use-pylint: false
-          # Use pycodestyle
-          use-pycodestyle: false
           # Extra options: flake8 $(extra-flake8-options) $(python-root-list)
           extra-flake8-options: "--max-line-length 120 --exclude __init__.py"
           # Extra options: black --check $(extra-black-options) $(python-root-list)
@@ -31,3 +26,8 @@ jobs:
           # extra-mypy-options: # optional, default is
           # Extra options: isort -rc $(extra-isort-options) $(python-root-list) -c --diff
           extra-isort-options: "--check-only"
+        run: |
+          if ! ./backend/scripts/lint.sh; then
+           echo "Linting failed."
+           exit 1
+          fi
